#include "ws2811pio.h"

#include <cstdlib>  
#include <cstdio>

extern "C" {
#include "ws2811.pio.h" // header autogenerated by CMake (see pico_generate_pio_header). 
                        // Manually generate it with pioasm -o c-sdk ws2811.pio > ws2811.pio.h

#include "hardware/timer.h"
#include "hardware/pio.h"
#include "pico/stdlib.h"
}



WS2811Pio::WS2811Pio(uint bps, uint8_t pin) {
    bool is_added = pio_claim_free_sm_and_add_program(&ws2811pio_program, &pio_, &sm_, &offset_);
    if (!is_added) { 
        assert("Failed to load pio program");
        std::abort(); 
    }
    
    ws2811pio_program_init(pio_, sm_, offset_ , pin, bps, false); 
    
}


WS2811Pio::~WS2811Pio() {
    pio_remove_program_and_unclaim_sm(&ws2811pio_program, pio_, sm_, offset_);
}



void WS2811Pio::test(size_t num_leds) {
        
   
    while (true) {
        for (uint i = 0; i < num_leds; i++) {
            pio_sm_put_blocking(pio_, sm_, WHITE.as_RGB());  // write word to TX FIFO
        }
        busy_wait_ms(2000);

        for (uint i = 0; i < num_leds; i++) {
            pio_sm_put_blocking(pio_, sm_, RED.as_RGB());  
        }
        busy_wait_ms(2000);

        for (uint i = 0; i < num_leds; i++) {
            pio_sm_put_blocking(pio_, sm_, LIME.as_RGB());  
        }
        busy_wait_ms(2000);

        for (uint i = 0; i < num_leds; i++) {
            pio_sm_put_blocking(pio_, sm_, BLUE.as_RGB());  
        }
        busy_wait_ms(2000);
    }
    
    
}


